In [3]:
import numpy as np
import pandas as pd
from astroquery.jplhorizons import Horizons
import astropy.units as u
from astropy.constants import c
import matplotlib.pyplot as plt
from astropy.coordinates import SkyCoord

In [4]:
def get_astroquery_function(name,loc):
    def get_target_RADEC(t):
        obj = Horizons(id = name, location = loc, epochs = t, id_type = 'majorbody')
        obj = obj.ephemerides()
        radec = np.array([float(obj['RA']),float(obj['DEC'])])
        return radec
    return get_target_RADEC    

In [5]:
def strip(x):
    temp = x.strip(" [")
    return temp.strip("]")
names = ['ID', 'smf-name', 'smf-filepath', 'reduction', 'JDUTC', 'RA', 'Dec', 'filter', 'exp-time', 'UVx', 'UVy', 'UVz', 'obseqx', 'obseqy', 'obseqz', 'obseclx', 'obseclsy', 'obseclz']
df = pd.read_csv("/Users/user/Irregular-Satellites/amalgamated_unique_exposure_reads.txt", names = names, converters={col : strip for col in ['UVx', 'UVz', 'obseqx', 'obseqz', 'obseclx', 'obseclz']})

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (4,5,6,8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [8]:
def ImageFinder(df,func,i):
    try: 
        time = float(df["JDUTC"][i])
        astrRD = func(time)
        print(astrRD)
        RADEC = np.array([float(df["RA"][i]),float(df["Dec"][i])])
        print(RADEC)
        if (RADEC[0]-3.2 <= astrRD[0] <= RADEC[0]+3.2) and (RADEC[1]-3.2 <= astrRD[1] <= RADEC[1]+3.2):
            return True,astrRD,RADEC,time
        else:
            return False,astrRD,RADEC,time
    except:
            return None,astrRD,RADEC,time

In [10]:
get_jup = get_astroquery_function("5","f51")
bools = []
QueryRADec = []
PANSTRADec = []
times = []

for i in (1290,1302,1307,1319,2213,2232):
    k = ImageFinder(df,get_jup,i)
    print(k,i)
    times.append(k[3])
    QueryRADec.append(k[1])
    PANSTRADec.append(k[2])

[329.35716 -13.35594]
[329.621607 -15.91217 ]
(True, array([329.35716, -13.35594]), array([329.621607, -15.91217 ]), 2454993.105564195) 1290
[329.35727 -13.35593]
[327.215788 -11.594384]
(True, array([329.35727, -13.35593]), array([327.215788, -11.594384]), 2454993.114031911) 1302
[329.35731 -13.35592]
[329.621239 -15.911818]
(True, array([329.35731, -13.35592]), array([329.621239, -15.911818]), 2454993.117372288) 1307
[329.35742 -13.35592]
[327.215873 -11.5952  ]
(True, array([329.35742, -13.35592]), array([327.215873, -11.5952  ]), 2454993.1260502716) 1319
[329.39793 -13.36958]
[329.686524 -13.076262]
(True, array([329.39793, -13.36958]), array([329.686524, -13.076262]), 2454999.077545891) 2213
[329.39786 -13.36966]
[329.686448 -13.076365]
(True, array([329.39786, -13.36966]), array([329.686448, -13.076365]), 2454999.090590185) 2232


In [12]:
QueryRADec

[array([329.35716, -13.35594]),
 array([329.35727, -13.35593]),
 array([329.35731, -13.35592]),
 array([329.35742, -13.35592]),
 array([329.39793, -13.36958]),
 array([329.39786, -13.36966])]

In [13]:
PANSTRADec

[array([329.621607, -15.91217 ]),
 array([327.215788, -11.594384]),
 array([329.621239, -15.911818]),
 array([327.215873, -11.5952  ]),
 array([329.686524, -13.076262]),
 array([329.686448, -13.076365])]

In [15]:
norms = []
for i in range(0,len(times)):
    distance = np.linalg.norm(QueryRADec[i]-PANSTRADec[i])
    norms.append(distance)

In [16]:
norms

[2.5698723759574085,
 2.772902714925324,
 2.5694888798056734,
 2.7724282626623555,
 0.41148747971235544,
 0.4114668768795403]

In [17]:
times

[2454993.105564195,
 2454993.114031911,
 2454993.117372288,
 2454993.1260502716,
 2454999.077545891,
 2454999.090590185]

In [63]:
df[1302:1303]

ID               smf-name  \
1302  1302   o4992g0312o.76255.cm   

                                           smf-filepath reduction  \
1302   ./smf_downloads/3PI.2009-06-10/o4992g0312o.76...    PS1_V5   

                   JDUTC           RA          Dec    filter exp-time  \
1302   2454993.114031911   327.215788   -11.594384   y.00000     30.0   

                     UVx       UVy                  UVz               obseqx  \
1302  0.8235609953495464 -0.530428  -0.2009819044762708  -0.1811335766755959   

       obseqy               obseqz              obseclx  obseclsy  \
1302 -0.91658  -0.3973361573938308  -0.1811335766755959 -0.998997   

                 obseclz  
1302  0.0000459613760628

In [64]:
obj = Horizons(id = '5', location = 'f51', epochs = 2454993.114031911, id_type = 'majorbody')
obj.ephemerides()

<Table masked=True length=1>
      targetname             datetime_str       ...  PABLon   PABLat
         ---                     ---            ...   deg      deg  
        str22                   str24           ... float64  float64
---------------------- ------------------------ ... -------- -------
Jupiter Barycenter (5) 2009-Jun-10 14:44:12.357 ... 321.5158 -0.8043

In [60]:
df['smf-filepath'][2232]

' ./smf_downloads/3PI.2009-06-16/o4998g0360o.78376.cm.1163824.smf'